// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThursdayMeetingBot.Libraries.Data.Contexts;

namespace ThursdayMeetingBot.Libraries.Data.MigrationStore.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20210731215945_InitialMigration")]
    partial class CreateChatTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ThursdayMeetingBot.Libraries.Data.Models.ChatType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_chat_types");

                    b.ToTable("chat_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "Private",
                            CreatedDate = new DateTime(2021, 7, 31, 21, 59, 45, 64, DateTimeKind.Utc).AddTicks(3689),
                            UpdatedDate = new DateTime(2021, 7, 31, 21, 59, 45, 64, DateTimeKind.Utc).AddTicks(3705)
                        },
                        new
                        {
                            Id = 2,
                            Alias = "Group",
                            CreatedDate = new DateTime(2021, 7, 31, 21, 59, 45, 64, DateTimeKind.Utc).AddTicks(6173),
                            UpdatedDate = new DateTime(2021, 7, 31, 21, 59, 45, 64, DateTimeKind.Utc).AddTicks(6181)
                        },
                        new
                        {
                            Id = 3,
                            Alias = "Channel",
                            CreatedDate = new DateTime(2021, 7, 31, 21, 59, 45, 64, DateTimeKind.Utc).AddTicks(6187),
                            UpdatedDate = new DateTime(2021, 7, 31, 21, 59, 45, 64, DateTimeKind.Utc).AddTicks(6189)
                        },
                        new
                        {
                            Id = 4,
                            Alias = "Supergroup",
                            CreatedDate = new DateTime(2021, 7, 31, 21, 59, 45, 64, DateTimeKind.Utc).AddTicks(6193),
                            UpdatedDate = new DateTime(2021, 7, 31, 21, 59, 45, 64, DateTimeKind.Utc).AddTicks(6194)
                        });
                });

            modelBuilder.Entity("ThursdayMeetingBot.Libraries.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
