// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThursdayMeetingBot.Libraries.Data.Contexts;

namespace ThursdayMeetingBot.Libraries.Data.MigrationStore.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20210802194050_DeleteChatsFromChatType")]
    partial class DeleteChatsFromChatType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ChatUser", b =>
                {
                    b.Property<long>("ChatsId")
                        .HasColumnType("bigint")
                        .HasColumnName("chats_id");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer")
                        .HasColumnName("users_id");

                    b.HasKey("ChatsId", "UsersId")
                        .HasName("pk_chat_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_chat_user_users_id");

                    b.ToTable("chat_user");
                });

            modelBuilder.Entity("ThursdayMeetingBot.Libraries.Data.Models.Chat", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("ChatTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_type_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_chats");

                    b.HasIndex("ChatTypeId")
                        .HasDatabaseName("ix_chats_chat_type_id");

                    b.ToTable("chats");
                });

            modelBuilder.Entity("ThursdayMeetingBot.Libraries.Data.Models.ChatType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_chat_types");

                    b.ToTable("chat_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "Private",
                            CreatedDate = new DateTime(2021, 8, 2, 19, 40, 50, 48, DateTimeKind.Utc).AddTicks(2412),
                            UpdatedDate = new DateTime(2021, 8, 2, 19, 40, 50, 48, DateTimeKind.Utc).AddTicks(2425)
                        },
                        new
                        {
                            Id = 2,
                            Alias = "Group",
                            CreatedDate = new DateTime(2021, 8, 2, 19, 40, 50, 48, DateTimeKind.Utc).AddTicks(3519),
                            UpdatedDate = new DateTime(2021, 8, 2, 19, 40, 50, 48, DateTimeKind.Utc).AddTicks(3521)
                        },
                        new
                        {
                            Id = 3,
                            Alias = "Channel",
                            CreatedDate = new DateTime(2021, 8, 2, 19, 40, 50, 48, DateTimeKind.Utc).AddTicks(3524),
                            UpdatedDate = new DateTime(2021, 8, 2, 19, 40, 50, 48, DateTimeKind.Utc).AddTicks(3524)
                        },
                        new
                        {
                            Id = 4,
                            Alias = "Supergroup",
                            CreatedDate = new DateTime(2021, 8, 2, 19, 40, 50, 48, DateTimeKind.Utc).AddTicks(3526),
                            UpdatedDate = new DateTime(2021, 8, 2, 19, 40, 50, 48, DateTimeKind.Utc).AddTicks(3527)
                        });
                });

            modelBuilder.Entity("ThursdayMeetingBot.Libraries.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ChatUser", b =>
                {
                    b.HasOne("ThursdayMeetingBot.Libraries.Data.Models.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThursdayMeetingBot.Libraries.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThursdayMeetingBot.Libraries.Data.Models.Chat", b =>
                {
                    b.HasOne("ThursdayMeetingBot.Libraries.Data.Models.ChatType", "ChatType")
                        .WithMany()
                        .HasForeignKey("ChatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatType");
                });
#pragma warning restore 612, 618
        }
    }
}
